version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          requires:
            - cypress/install
          start: npm start
          wait-on: 'http://localhost:3000'