version: 2.1
orbs:
  cypress: cypress-io/cypress@2.0.0
  codecov: codecov/codecov@1.2.3 #

executors:
  with-chrome-and-firefox:
    docker:
      - image: "cypress/browsers:node16.14.2-slim-chrome100-ff99-edge"
    resource_class: large

workflows:
  cypress:
    jobs:
    - cypress/install:
        name: "Setup Linux"
        yarn: true
        executor: with-chrome-and-firefox

    - cypress/run:
        name: "UI Tests - Chrome"
        browser: chrome
        spec: cypress/e2e/*
        executor: with-chrome-and-firefox
        wait-on: "http://localhost:3000"
        yarn: true
        start: npm run start
        ci-build-id: ${CIRCLE_SHA1:0:8}
        requires:
          - Setup Linux
