version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16.0-browsers
    working_directory: ~/repo
workflows:
  build:
    jobs:
      - cypress/run:
          requires:
            - cypress/install
          start: npm start
          wait-on: "http://localhost:3000"
