version: 2.1
orbs:
  cypress: cypress-io/cypress@1
steps:
  - checkout:
    path: ~/SmallProjects/MoviesProject & pwd
  - restore_cache:
    keys:
      - v1-dependencies-{{ checksum "MoviesProject/package.json" }}
      - v1-dependencies-
  - run: npm install
workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:
          requires:
            - cypress/install
          working_directory: ~/SmallProjects/MoviesProject
          start: npm start
          wait-on: "http://localhost:3000"
